# Use the official Golang image as the base image
FROM golang:1.21.6-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the Go module files
COPY go.mod go.sum ./

# Download and install the Go dependencies
RUN go mod download

# Copy the source code into the container
COPY . .

# Perform go mod tidy and go mod vendor
RUN go mod tidy

# Build the Go application
RUN go build -o main ./cmd/example-app

# Set the entry point for the container
CMD ["./main"]